### ISSUE TITLE
Home page -081/"When the user clicks on a movie, they are directed to the  next page where the website logo is visible."

### ISSUE THREAD

**Issue by abdulkalam0091** [Kotti13/ticketboxx#10]
![Screenshot (104)](https://github.com/user-attachments/assets/336804a1-16ac-4b73-a518-d3c9e20a255d)

**Comment by Kotti13** [comment]
"Thank you for reporting the issue. It has been resolved and the logo now displays correctly on the movie detail page."

**Comment by Kotti13** [comment]
"Thank you for reporting the issue. It has been resolved and the logo now displays correctly on the movie detail page."

**Comment by abdulkalam0091** [comment]
ok i check
