### ISSUE TITLE
"Clicking the search button displays the typed input on the  website."

### ISSUE THREAD

**Issue by abdulkalam0091** [Kotti13/ticketboxx#5]
![Screenshot (89)](https://github.com/user-attachments/assets/ec8e0db4-d520-40f3-883c-f78849fa2213)
![Screenshot (90)](https://github.com/user-attachments/assets/1a4669cb-93a1-4765-af72-afce67e24277)

user search movie not found

**Comment by Kotti13** [comment]
The issue has been resolved, please verify the updates.

**Comment by abdulkalam0091** [comment]
ok bro
