### ISSUE TITLE
Home page -062/"The login page should display options to  log in using Google or GitHub accounts."

### ISSUE THREAD

**Issue by abdulkalam0091** [Kotti13/ticketboxx#6]
![Screenshot (91)](https://github.com/user-attachments/assets/32993923-ad7d-49c0-ab17-38e74d921a48)
not able to log in with GitHub and Google

**Comment by Kotti13** [comment]
this bug resolved please recheck

**Comment by abdulkalam0091** [comment]
Ok. I checked bug cleared
