### ISSUE TITLE
Home page -067/"Clicking ""Movies"" in the navigation bar  displays the movie slider, allowing  users to select a movie."

### ISSUE THREAD

**Issue by abdulkalam0091** [Kotti13/ticketboxx#7]
![Screenshot (92)](https://github.com/user-attachments/assets/c512737d-fef5-4093-93d7-c8b7477321b4)

"The user clicked on one movie, but another movie is showing."

**Comment by Kotti13** [comment]
please recheck resolved this error.

**Comment by abdulkalam0091** [comment]
I checked now its working
