### ISSUE TITLE
Home page -072/"Typing special characters in the name  input box displays the error message:  ""The name is not valid.""           

### ISSUE THREAD

**Issue by abdulkalam0091** [Kotti13/ticketboxx#9]
![Screenshot (95)](https://github.com/user-attachments/assets/449c3044-5941-45a8-abca-d7c74ffca4e6)

"The user entered only special characters, which is not a valid name."

**Comment by Kotti13** [comment]
I fixed this problem please recheck.

**Comment by abdulkalam0091** [comment]
Ok
